GNN_hidden_dim: 32
K: 10
act_GNN_hidden_dim: 32
action_masking: true
activation_function: relu
batch_size: 128
config_file: PST_V2G_ProfixMax_25.yaml
dataset: optimal_25_1000
device: cuda:0
dropout: 0.1
embed_dim: 128
env: PST_V2G_ProfixMax
eval_replay_path: ./eval_replays/PST_V2G_ProfixMax_25_optimal_25_50/
feature_dim: 8
group_name: PaperExps
learning_rate: 0.0001
log_to_wandb: true
max_iters: 250
mode: normal
model_type: gnn_act_emb
n_head: 4
n_layer: 3
name: gnn_act_emb_run_40_K=10_dataset=optimal_25_1000_25724
num_act_gcn_layers: 3
num_eval_episodes: 30
num_gcn_layers: 3
num_steps_per_iter: 1000
pct_traj: 1.0
seed: 40
warmup_steps: 10000
weight_decay: 0.0001
