K: 2
activation_function: relu
batch_size: 128
config_file: PST_V2G_ProfixMax_25.yaml
dataset: optimal_1000
device: cuda:0
discount: 0.99
dropout: 0.1
early_epoch: 100
early_stop: false
embed_dim: 128
env: PST_V2G_ProfixMax_1000
eta: 0.05
eta2: 1.0
eval_replay_path: ./eval_replays/PST_V2G_ProfixMax_25_optimal_25_50/
grad_norm: 15.0
group_name: PaperExps
infer_no_q: false
k_rewards: true
lambda: 1.0
learning_rate: 0.0003
log_to_wandb: true
lr_decay: true
lr_min: 0.0
max_iters: 250
max_q_backup: false
mode: normal
n_head: 4
n_layer: 3
name: QT_run_30_K=2_dataset=optimal_1000_87175
num_eval_episodes: 30
num_steps_per_iter: 1000
pct_traj: 1.0
reward_tune: 'no'
rtg_no_q: false
sar: false
save_path: ./save/
scale: 1
seed: 30
tau: 0.005
test_scale: 1
use_discount: true
warmup_steps: 10000
weight_decay: 0.0001
